### ISSUE TITLE
util.print: Use console.log instead

### ISSUE THREAD

**Issue by SirWilli** [DTrejo/run.js#38]
Hey,
if I use run.js it shows this message "util.print: Use console.log instead" for each log in the console.

How you can see here:
![image](https://cloud.githubusercontent.com/assets/5961995/6750186/16013c86-cef8-11e4-9739-300341ad84b7.png)

Do I need to use util.print instead of console.log or whats the issue?

**Comment by DTrejo** [comment]
The issue is that I am using util.print to take the output from your program and print it to your console.

run.js should instead be using `process.stdout.write`

Thanks for the report! I will be fixing it in a few hours, unless you beat me to it ;)

QUESTION: I am working on a 2.0 version of run.js — would you prefer it to replace the current run.js? Or prefer a new/different project?

Cheers,
D

**Comment by SirWilli** [comment]
Thanks that fixed it.

Depends, if it is not completly different I would replace it.

**Comment by DTrejo** [comment]
It does mostly the same thing.

Thanks for the advice.

I think I will replace it because it is much more modern, and I want to
re-use the name.

It does remove some features like coffeescript support, at least for now.

You can see the slow work in progress:
https://github.com/DTrejo/run.js/tree/2.0

Cheers,
D

On Fri, Mar 20, 2015 at 8:16 AM, SirWilli <notifications@github.com> wrote:

> Thanks that fixed it.
>
> Depends, if it is not completly different I would replace it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DTrejo/run.js/issues/38#issuecomment-84043405>.
>



-- 
See my projects at dtrejo.com
Read my tips for developers dtrejo.com/blog

**Comment by DTrejo** [comment]
just published 1.4.0 which fixes this!
D

On Sun, Mar 22, 2015 at 4:04 AM, SirWilli <notifications@github.com> wrote:

> Closed #38 <https://github.com/DTrejo/run.js/issues/38>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DTrejo/run.js/issues/38#event-261539107>.
>



-- 
See my projects at dtrejo.com
Read my tips for developers dtrejo.com/blog

**Comment by SirWilli** [comment]
Thanks, I changed it locally too so I don't need to update ;)
